max_default_generators: 25
# Color schemes you can use via <(color name)>
colors:
  main: '#002855'
  light: '#0466C8'
  dull: '#979DAC'
messages:
  prefix: '<main>OrbitalGN</main> <dull>></dull> '
  sell.success: "<gray>Sold all of your generator drops for <color:#72fb00><value></color>!</gray>"
  sell.no_items: '<gray>You do not have any items to sell.</gray>'
  gens.no_slots: 'You do not have enough generator slots.'
  gens.place: '<white>Successfully placed generator</white> <gray>(<green><placed></green>/<red><max></red>)</gray>'
generators:
  coal_generator:
    generator_name: <gray>Coal Generator</gray>
    generator_block: coal_ore
    generator_lore: <red>Generates coal</red>
    drop_name: <blue>Coal</blue>
    drop_item: coal
    drop_value: 10
    upgrade_cost: 100
  iron_generator:
    generator_name: <white>Iron Generator</white>
    generator_block: iron_ore
    generator_lore: <red>Generates iron</red>
    drop_name: <green>Iron Ingot</green>
    drop_item: iron_ingot
    drop_value: 20
    upgrade_cost: 200
